# Generated by Django 4.1.1 on 2022-09-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctors_pr_number", models.CharField(max_length=255, null=True)),
                ("doctors_name", models.CharField(max_length=255, null=True)),
                (
                    "doctors_group",
                    models.CharField(
                        choices=[
                            ("A", "GROUP A"),
                            ("B", "GROUP B"),
                            ("C", "GROUP C"),
                            ("D", "GROUP D"),
                            ("E", "GROUP E"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "doctor_status",
                    models.CharField(
                        choices=[
                            (
                                "ACTIVE",
                                "DOCTOR IS CURRENTLY WORKING WITH THE ORGANIZATION",
                            ),
                            ("QUITTED", "DOCTOR HAS LEFT THE ORGANIZATION"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
