# Generated by Django 4.1.1 on 2022-09-21 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payout_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transplant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctors_share", models.IntegerField(null=True)),
                ("doctors_department", models.CharField(max_length=255, null=True)),
                (
                    "doctors_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payout_app.doctorprofile",
                    ),
                ),
            ],
        ),
    ]
