# Generated by Django 4.1.1 on 2022-09-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payout_app", "0002_transplant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transplant",
            name="doctors_share",
            field=models.FloatField(null=True),
        ),
    ]
