# Generated by Django 4.2.1 on 2023-05-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout_app', '0003_alter_transplant_doctors_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(help_text='Enter the name of the query', unique=True, verbose_name='Query Name')),
                ('query', models.TextField(help_text='Enter the name of the query', unique=True, verbose_name='Query Name')),
            ],
        ),
    ]
