services:
  app:
    build: .
    restart: always
    image: doctor_payout_image
    container_name: doctor_payout_container
    volumes:
      - .:/doctors_payout
    ports:
      - 8008:8008
    depends_on:
      - doctor_payout_node

  doctor_payout_node:
    build:
      context: ../doctors_payout_sveltekit
    restart: always
    image: doctor_svelte_image
    container_name: doctor_payout_svelte_container
    volumes:
      - ../doctors_payout_sveltekit:/doctors_payout_sveltekit
    ports:
      - 8007:8007
