services:
  app:
    build: .
    restart: always
    image: doctor_payout_image
    container_name: doctor_payout_container
    volumes:
      - .:/doctors_payout
    env_file:
      - .env
    ports:
      - 8008:8008
    depends_on:
      - postgres

  doctor_payout_node:
    build:
      context: ../doctors_payout_sveltekit
    restart: always
    image: doctor_svelte_image
    container_name: doctor_payout_svelte_container
    volumes:
      - ../doctors_payout_sveltekit:/doctors_payout_sveltekit
    env_file:
      - .env
    ports:
      - 8007:8007
    depends_on:
      - app

  postgres:
    build:
      context: ./postgresql
    image: doctors_payout_postgresql_image
    container_name: doctors_payout_postgresql_container
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    env_file:
      - .env